name: "Ecosense (pyiu)"
description: "Modified version of starsoccer's Ecosense EcoQube addon (https://github.com/starsoccer/ecosense), with added support for simultaneous output of radon measurements in Bq/m³ and pCi/L."
version: "0.0.2"
slug: "ecosense"
arch:
  - aarch64
  - amd64
  - armv7
ports:
  443/tcp: 443
ports_description:
  443/tcp: HTTPS webserver port
options:
  mqtt_port: 1883
  mqtt_host: null
  mqtt_username: null
  mqtt_password: null
  log_level: "info"
  dns_refresh_frequency: 1440
schema:
  mqtt_port: port
  mqtt_host: str
  mqtt_username: str
  mqtt_password: password
  log_level: list(fatal|error|warn|info|debug|trace)
  dns_refresh_frequency: int
