name: "Ecosense"
description: "Ecosense"
version: "0.0.3"
slug: "ecosense"
image: "ghcr.io/starsoccer/ecosense/{arch}"
arch:
  - aarch64
  - amd64
  - armv7
ports:
  443/tcp: 443
ports_description:
  443/tcp: HTTPS webserver port
options:
  mqtt_port: 1883
  mqtt_host: null
  mqtt_username: null
  mqtt_password: null
  log_level: "info"
  dns_refresh_frequency: 1440
schema:
  mqtt_port: port
  mqtt_host: str
  mqtt_username: str
  mqtt_password: password
  log_level: list(fatal|error|warn|info|debug|trace)
  dns_refresh_frequency: int
